name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "tv.thinh2000@gmail.com" && git config --global user.name "Van Thinh"

      - name: Create Release
        id: create_release
        run: |
          tag=$(date +'%Y%m%d%H%M%S')
          git tag $tag
          git push origin $tag
          echo "::set-output name=tag::$tag"

  deploy:
    runs-on: ubuntu-latest

    needs: create_release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
