name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "tv.thinh2000@gmail.com"
          git config --global user.name "Van Thinh"

      - name: Get Committer Information
        id: commit_info
        run: echo "::set-output name=author::$(git log -1 --pretty=format:'%an')"

      - name: Create Release
        id: create_release
        run: |
          branch=$(echo "${GITHUB_REF#refs/heads/}")
          version=$(echo "v$(date +'%Y.%m.%d.%H%M%S')-${{ steps.commit_info.outputs.author }}-${branch}")
          git tag $version
          git push origin $version
          echo "::set-output name=version::$version"

  deploy:
    runs-on: ubuntu-latest

    needs: create_release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Get GitHub Pages URL
        id: pages_url
        run: echo "::set-output name=url::https://${GITHUB_REPOSITORY}.github.io/${{ steps.deploy.outputs.repo_name }}/"

  update_readme:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Get Repository Name
        run: echo "::set-output name=repo_name::$(basename $GITHUB_REPOSITORY)"
        id: repo_name

      - name: Update README
        run: |
          echo "Deployed GitHub Pages: https://${{ steps.repo_name.outputs.repo_name }}.github.io/${GITHUB_REPOSITORY#*/}/" >> README.md
          git add README.md
          git config --global user.email "tv.thinh2000@gmail.com"
          git config --global user.name "Van Thinh"
          git commit -m "Update README with GitHub Pages URL"
          git push origin main
