name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    outputs:
      # Declare an output named 'author' to pass data between steps
      id: commit_info
      set-env:
        # Set an environment variable 'AUTHOR' to make it accessible to subsequent steps
        AUTHOR: ${{ steps.commit_info.outputs.author }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "tv.thinh2000@gmail.com"
          git config --global user.name "Van Thinh"

      - name: Get Committer Information
        id: commit_info
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_PATH/commit_info

      - name: Create Release
        id: create_release
        run: |
          branch=$(echo "${GITHUB_REF#refs/heads/}")
          version=$(echo "v$(date +'%Y.%m.%d.%H%M%S')-${{ env.AUTHOR }}-${branch}")
          echo "version=${version}" >> $GITHUB_ENV
          git tag $version
          git push origin $version

  deploy:
    runs-on: ubuntu-latest

    needs: create_release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
